# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  name: : 

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: Docker@2
  inputs:
    containerRegistry: 'DockerHub'
    repository: 'shira'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    buildContext: '.'